#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL jMAVSim
#
# @type Quadrotor Wide
#
# @maintainer Julian Oes <julian@oes.ch>
#

. ${R}etc/init.d/rc.mc_defaults

param set-default CA_AIRFRAME 0

param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.1515
param set-default CA_ROTOR0_PY 0.245
param set-default CA_ROTOR0_KM 0.05
param set-default CA_ROTOR1_PX -0.1515
param set-default CA_ROTOR1_PY -0.1875
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR2_PX 0.1515
param set-default CA_ROTOR2_PY -0.245
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.1515
param set-default CA_ROTOR3_PY 0.1875
param set-default CA_ROTOR3_KM -0.05

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104

# Enable a stationary landing target estimator for SITL learning/log analysis.
param set-default VTE_EN 0
param set-default LTEST_MODE 1
param set-default LTEST_SENS_ROT 0
param set-default LTEST_SIM_EN 1
param set-default LTEST_SIM_X 0.0
param set-default LTEST_SIM_Y 0.0
param set-default LTEST_Z_FALLBACK 1
param set-default PLD_HACC_RAD 0.1
param set-default RTL_PLD_MD 2

if param compare VTE_EN 0
then
	landing_target_estimator start
fi
